/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rayn' at '10/28/16 6:15 PM' with Gradle 2.14.1
 *
 * @author rayn, @date 10/28/16 6:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
